### ISSUE TITLE
Renderer contains shared state

### ISSUE THREAD

**Issue by sponiro** [redfx-quantum/strangefx#59]
The class org.redfx.strangefx.render.Renderer contains a static variable myStage. When executing the example from https://github.com/johanvos/quantumjava and the class org.redfx.javaqc.ch05.cnot.Main the results displayed are not what was calculated.
I suspect the shared variable leads to multiple overrides of some displayed variables. The visible results might even change for each execution. Also, the barchart which is only visible for one window backs up this theory.
When I start only one part of the program like run10(); and comment the others the display is correct.

![StrangeFX-1](https://user-images.githubusercontent.com/507613/107121321-144c7100-6892-11eb-8c44-28e448f8e3ff.png)
![StrangeFX-2](https://user-images.githubusercontent.com/507613/107121322-14e50780-6892-11eb-826d-7b1d01dc7c2f.png)
![StrangeFX-3](https://user-images.githubusercontent.com/507613/107121323-14e50780-6892-11eb-9f78-45ded3c819b7.png)
![StrangeFX-4](https://user-images.githubusercontent.com/507613/107121324-14e50780-6892-11eb-9653-8b813d372533.png)

**Comment by johanvos** [comment]
Thanks for the report. The `myStage` should be fine, but I realize that the endStates are now static:

`        ObservableList<Double> endStates = Model.getInstance().getEndStates();
`
I'll fix it, good catch!

**Comment by johanvos** [comment]
Fixed by #61
